### ISSUE TITLE
Require PHP 5.6

### ISSUE THREAD

**Issue by h4kuna** [FreezyBee/MojeId#2]
What source codes are incompatble with php 5.4?

**Comment by janatjak** [comment]
It should be compatible i think.
(But I develop on PHP7-RC6)

**Comment by h4kuna** [comment]
Some tests and travis help to keep compatible for more php versions. Now looks like is compatible and README is misleading.

**Comment by janatjak** [comment]
tests and travis tests are in roadmap...

**Comment by h4kuna** [comment]
:+1:
