### ISSUE TITLE
Redirect na mojeid nefunguje

### ISSUE THREAD

**Issue by jirinapravnik** [FreezyBee/MojeId#3]
Je tohle rozšíření stále funkční? Když se máí přesměrovat na mojeid, tak se tak nestane, problém je dle mě zde: https://github.com/FreezyBee/MojeId/blob/master/src/MojeId.php#L176 . Nebo dělám něco špatně?

**Comment by janatjak** [comment]
Podle tohoto popisu tezko rici. Dle meho skromneho nazoru stale funguje...

**Comment by jirinapravnik** [comment]
Ono neni moc co konkretizovat:-) Mam Nette 2.3, a když má dojít k redirectu, k žádnému nedojde, dostanu pouze bílou stránku.

Zkusil jsem ten řádek, změnit na:
$this->httpResponse->redirect($redirectUrl); 

a zdá se, že to funguje jak má, až to kdyžtak testnu více, poslal bych PR
